// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import constants from '../constant'

let awsmobile = null;
let s3 = null;

awsmobile = {
    region: "ap-south-1"
};

s3 = {
    bucket: constants.INGESTION_BUCKET,
    region: constants.REGION
};

const awsExports = {
    Auth: awsmobile,
    Storage: {
        AWSS3: s3
    }
};

export default awsExports;
